Feat: Clusters
geonativefr/vue3-leaflet pull request #11
Opened 2022-11-23 15:50 UTC by bpolaszek

2022-11-23 16:40 UTC, misaert requested changes

2022-11-23 16:40 UTC, misaert commented on src/utils/leaflet-markercluster-loader.js
> +    loadJSFromCDN(`https://unpkg.com/leaflet.markercluster@1.4.1/dist/leaflet.markercluster.js`),
`${version}`, right?

2022-11-24 09:15 UTC, bpolaszek commented on src/utils/leaflet-markercluster-loader.js
> +    loadJSFromCDN(`https://unpkg.com/leaflet.markercluster@1.4.1/dist/leaflet.markercluster.js`),
Good catch!

2022-11-24 09:32 UTC, misaert approved these changes

2022-11-24 09:33 UTC, merged